package org.vaadin.designerdemo.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SidebarButtonDesign extends HorizontalLayout {
	protected Button nameButton;
	protected TextField nameTextField;
	protected Button editButton;
	protected Button deleteButton;
	protected Button saveEditButton;
	protected Button cancelEditButton;

	public SidebarButtonDesign() {
		Design.read(this);
	}
}
